//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskUtility.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileTable
    {
        public long Id { get; set; }
        public string TableName { get; set; }
        public string SheetName { get; set; }
        public string ColumnMin { get; set; }
        public string ColumnMax { get; set; }
        public int RowMin { get; set; }
        public int RowMax { get; set; }
        public long TemplateId { get; set; }
    
        public virtual FileTemplate FileTemplate { get; set; }
    }
}
