//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskUtility.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FileTemplate()
        {
            this.FileTables = new HashSet<FileTable>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public int CountryId { get; set; }
        public byte[] Template { get; set; }
        public string Extention { get; set; }
    
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileTable> FileTables { get; set; }
    }
}
