//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskUtility
{
    using System;
    using System.Collections.Generic;
    
    public class Email
    {
        public long Id { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public string Country { get; set; }
        public string To { get; set; }
        public string From { get; set; }
        public List<string> cc { get; set; }
    }
}
